/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Al usar 'autogenerated', Docusaurus leerá automáticamente cualquier 
  // carpeta o archivo nuevo que se cree desde el CMS y armará el menú.
  docsSidebar: [
    {
      type: 'autogenerated', 
      dirName: '.', // El punto significa "escanea toda la carpeta /docs"
    }
  ],
};

export default sidebars;
