/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Docusaurus leerá automáticamente cualquier carpeta o archivo 
  // nuevo que se cree desde el CMS y armará el menú.
  tutorialSidebar: [
    {
      type: 'autogenerated', 
      dirName: '.', 
    }
  ],
};

module.exports = sidebars;
