# Conexión directa a GitHub usando tu proveedor OAuth de Netlify
backend:
  name: github
  repo: UlisesGutierrez2/piloto-cms
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth

# Flujo de trabajo editorial (Habilita la creación de Pull Requests de forma nativa)
publish_mode: editorial_workflow
# Configuración global de medios (Fallback)
media_folder: "static/videos" # SIN barra inicial
public_folder: "/videos"      # CON barra inicial

collections:
  # --- 1. COLECCIÓN: ONBOARDING ---
  - name: "onboarding"
    label: "Onboarding"
    label_singular: "Documento de Onboarding"
    folder: "docs/onboarding"
    create: true
    extension: "md"
    format: "frontmatter"
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: '📂 Directorio de guardado (Opcional)'
        index_file: 'index'
    
    # Almacén específico para Onboarding
    media_folder: "/static/videos/onboarding" # SIN barra inicial (Va a la raíz del repo)
    public_folder: "/videos/onboarding"      # CON barra inicial (Va a la raíz de la web)
    
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - label: "Cuerpo del texto"
        name: "body"
        widget: "markdown"
        buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "quote", "bulleted-list", "numbered-list"]
        editor_components: ["image-renderer-component", "video"]

  # --- 2. COLECCIÓN: LINEAMIENTOS ---
  - name: "lineamientos"
    label: "Lineamientos"
    label_singular: "Documento de Lineamientos"
    folder: "docs/lineamientos"
    create: true
    extension: "md"
    format: "frontmatter"
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: '📂 Directorio de guardado (Opcional)'
        index_file: 'index'

    # Almacén específico para Lineamientos
    media_folder: "/static/videos/lineamientos" # SIN barra inicial (Va a la raíz del repo)
    public_folder: "/videos/lineamientos"      # CON barra inicial (Va a la raíz de la web)
    
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - label: "Cuerpo del texto"
        name: "body"
        widget: "markdown"
        buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "quote", "bulleted-list", "numbered-list"]
        editor_components: ["image-renderer-component", "video"]
