# Conexión a tu repositorio
backend:
  name: github
  repo: UlisesGutierrez2/piloto-cms
  branch: main

# Flujo de trabajo con Pull Requests
publish_mode: editorial_workflow

# Imágenes globales
media_folder: "static/img"
public_folder: "/img"

collections:
  # --- 1. COLECCIÓN: ONBOARDING ---
  - name: "onboarding"
    label: "Onboarding"
    folder: "docs/onboarding"
    create: true
    extension: "md"
    format: "frontmatter"
    # Soporte para tus múltiples niveles de subcarpetas
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: 'index'
    media_folder: "static/img/onboarding"
    public_folder: "/img/onboarding"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Cuerpo del texto", name: "body", widget: "markdown"}

  # --- 2. COLECCIÓN: LINEAMIENTOS ---
  - name: "lineamientos"
    label: "Lineamientos"
    folder: "docs/lineamientos"
    create: true
    extension: "md"
    format: "frontmatter"
    # Soporte para tus múltiples niveles de subcarpetas
    nested:
      depth: 10
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: 'index'
    media_folder: "static/img/lineamientos"
    public_folder: "/img/lineamientos"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Cuerpo del texto", name: "body", widget: "markdown"}
