backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

# 1. Configuración Global (Fallback por si creas una colección sin ruta específica)
media_folder: "static/img"
public_folder: "/img"

collections:
  # --- COLECCIÓN: ONBOARDING ---
  - name: "onboarding"
    label: "Onboarding"
    folder: "docs/onboarding" # Dónde se guardan los .mdx
    create: true
    nested:
      depth: 3
    # 2. La magia ocurre aquí: Redirigimos los archivos multimedia de esta colección
    media_folder: "static/img/onboarding"
    public_folder: "/img/onboarding"
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: 'index'
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Cuerpo del texto", name: "body", widget: "markdown"}

  # --- COLECCIÓN: LINEAMIENTOS ---
  - name: "lineamientos"
    label: "Lineamientos"
    folder: "docs/lineamientos"
    create: true
    nested:
      depth: 3
    # Mapeo específico para imágenes de lineamientos
    media_folder: "static/img/lineamientos"
    public_folder: "/img/lineamientos"
    meta:
      path:
        widget: string
        label: 'Path'
        index_file: 'index'
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Cuerpo del texto", name: "body", widget: "markdown"}
